---
name: SOAP-WSDL
version: 1.25
author: []
abstract: WSDL support for SOAP::Lite
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  SOAP::Lite: 0
  XML::XPath: 0
provides:
  SOAP::WSDL:
    file: lib/SOAP/WSDL.pm
    version: 1.25
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
