
package MyElements::AddAttachmentResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://tempuri2.org/' }

__PACKAGE__->__set_name('AddAttachmentResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %AddAttachmentResult_of :ATTR(:get<AddAttachmentResult>);

__PACKAGE__->_factory(
    [ qw(        AddAttachmentResult

    ) ],
    {
        'AddAttachmentResult' => \%AddAttachmentResult_of,
    },
    {
        'AddAttachmentResult' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'AddAttachmentResult' => 'AddAttachmentResult',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

MyElements::AddAttachmentResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
AddAttachmentResponse from the namespace http://tempuri2.org/.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * AddAttachmentResult

 $element->set_AddAttachmentResult($data);
 $element->get_AddAttachmentResult();




=back


=head1 METHODS

=head2 new

 my $element = MyElements::AddAttachmentResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   AddAttachmentResult =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

