
package MyElements::AddUsersToGroupResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://tempuri2.org/' }

__PACKAGE__->__set_name('AddUsersToGroupResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %AddUsersToGroupResult_of :ATTR(:get<AddUsersToGroupResult>);

__PACKAGE__->_factory(
    [ qw(        AddUsersToGroupResult

    ) ],
    {
        'AddUsersToGroupResult' => \%AddUsersToGroupResult_of,
    },
    {

        'AddUsersToGroupResult' => 'MyElements::AddUsersToGroupResponse::_AddUsersToGroupResult',
    },
    {

        'AddUsersToGroupResult' => 'AddUsersToGroupResult',
    }
);

} # end BLOCK




package MyElements::AddUsersToGroupResponse::_AddUsersToGroupResult;
use strict;
use warnings;
{
our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables


__PACKAGE__->_factory(
    [ qw(
    ) ],
    {
    },
    {
    },
    {

    }
);

} # end BLOCK






}





} # end of BLOCK



1;


=pod

=head1 NAME

MyElements::AddUsersToGroupResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
AddUsersToGroupResponse from the namespace http://tempuri2.org/.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * AddUsersToGroupResult

 $element->set_AddUsersToGroupResult($data);
 $element->get_AddUsersToGroupResult();




=back


=head1 METHODS

=head2 new

 my $element = MyElements::AddUsersToGroupResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   AddUsersToGroupResult =>  {
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

