
package MyElements::ClearGroupResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://tempuri2.org/' }

__PACKAGE__->__set_name('ClearGroupResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ClearGroupResult_of :ATTR(:get<ClearGroupResult>);

__PACKAGE__->_factory(
    [ qw(        ClearGroupResult

    ) ],
    {
        'ClearGroupResult' => \%ClearGroupResult_of,
    },
    {

        'ClearGroupResult' => 'MyElements::ClearGroupResponse::_ClearGroupResult',
    },
    {

        'ClearGroupResult' => 'ClearGroupResult',
    }
);

} # end BLOCK




package MyElements::ClearGroupResponse::_ClearGroupResult;
use strict;
use warnings;
{
our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables


__PACKAGE__->_factory(
    [ qw(
    ) ],
    {
    },
    {
    },
    {

    }
);

} # end BLOCK






}





} # end of BLOCK



1;


=pod

=head1 NAME

MyElements::ClearGroupResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
ClearGroupResponse from the namespace http://tempuri2.org/.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ClearGroupResult

 $element->set_ClearGroupResult($data);
 $element->get_ClearGroupResult();




=back


=head1 METHODS

=head2 new

 my $element = MyElements::ClearGroupResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   ClearGroupResult =>  {
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

