package MyTypes::ArrayOfNUser;
use strict;
use warnings;


our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %NUser_of :ATTR(:get<NUser>);

__PACKAGE__->_factory(
    [ qw(        NUser

    ) ],
    {
        'NUser' => \%NUser_of,
    },
    {
        'NUser' => 'MyTypes::NUser',
    },
    {

        'NUser' => 'NUser',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::ArrayOfNUser

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ArrayOfNUser from the namespace http://tempuri2.org/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * NUser




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::ArrayOfNUser
   NUser =>  { value => $some_value },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

