package MyTypes::ArrayOfAttachment;
use strict;
use warnings;


our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Attachment_of :ATTR(:get<Attachment>);

__PACKAGE__->_factory(
    [ qw(        Attachment

    ) ],
    {
        'Attachment' => \%Attachment_of,
    },
    {
        'Attachment' => 'MyTypes::Attachment',
    },
    {

        'Attachment' => 'Attachment',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::ArrayOfAttachment

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ArrayOfAttachment from the namespace http://tempuri2.org/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Attachment




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::ArrayOfAttachment
   Attachment =>  { # MyTypes::Attachment
     Data =>  $some_value, # base64Binary
     Operation => $some_value, # AttachmentOperation
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

