package MyTypes::CountListOfSerializedItem;
use strict;
use warnings;


our $XML_ATTRIBUTE_CLASS = 'MyTypes::CountListOfSerializedItem::_CountListOfSerializedItem::XmlAttr';

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %List_of :ATTR(:get<List>);

__PACKAGE__->_factory(
    [ qw(        List

    ) ],
    {
        'List' => \%List_of,
    },
    {
        'List' => 'MyTypes::ArrayOfSerializedItem',
    },
    {

        'List' => 'List',
    }
);

} # end BLOCK




package MyTypes::CountListOfSerializedItem::_CountListOfSerializedItem::XmlAttr;
use base qw(SOAP::WSDL::XSD::Typelib::AttributeSet);

{ # BLOCK to scope variables

my %Count_of :ATTR(:get<Count>);

__PACKAGE__->_factory(
    [ qw(
        Count
    ) ],
    {

        Count => \%Count_of,
    },
    {
        Count => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
    }
);

} # end BLOCK



1;


=pod

=head1 NAME

MyTypes::CountListOfSerializedItem

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
CountListOfSerializedItem from the namespace http://tempuri2.org/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * List




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::CountListOfSerializedItem
   List =>  { # MyTypes::ArrayOfSerializedItem
     SerializedItem =>  { # MyTypes::SerializedItem
       Attachments =>  { # MyTypes::ArrayOfString1
         Attachment =>  $some_value, # string
       },
       Fields =>  { # MyTypes::ArrayOfField
         Field => ,
       },
     },
   },
 },



=head2 attr

NOTE: Attribute documentation is experimental, and may be inaccurate.
See the correspondent WSDL/XML Schema if in question.

This class has additional attributes, accessibly via the C<attr()> method.

attr() returns an object of the class MyTypes::CountListOfSerializedItem::_CountListOfSerializedItem::XmlAttr.

The following attributes can be accessed on this object via the corresponding
get_/set_ methods:

=over

=item * Count



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::int|SOAP::WSDL::XSD::Typelib::Builtin::int>.


=back




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

