package MyTypes::HashMapOfStringNiceListOfAddressesSalutations;
use strict;
use warnings;


our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %KVS_of :ATTR(:get<KVS>);

__PACKAGE__->_factory(
    [ qw(        KVS

    ) ],
    {
        'KVS' => \%KVS_of,
    },
    {
        'KVS' => 'MyTypes::KVstringNiceListOfAddressesSalutations',
    },
    {

        'KVS' => 'KVS',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::HashMapOfStringNiceListOfAddressesSalutations

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
HashMapOfStringNiceListOfAddressesSalutations from the namespace http://tempuri2.org/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * KVS




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::HashMapOfStringNiceListOfAddressesSalutations
   KVS =>  { # MyTypes::KVstringNiceListOfAddressesSalutations
     V =>  { # MyTypes::AddressesSalutations
       Recipients =>  { # MyTypes::Recipients
         To =>  $some_value, # string
         Cc =>  $some_value, # string
         Bcc =>  $some_value, # string
       },
       Salutation =>  $some_value, # string
     },
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

