package MyTypes::KVstringNiceListOfAddressesSalutations;
use strict;
use warnings;


our $XML_ATTRIBUTE_CLASS = 'MyTypes::KVstringNiceListOfAddressesSalutations::_KVstringNiceListOfAddressesSalutations::XmlAttr';

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %V_of :ATTR(:get<V>);

__PACKAGE__->_factory(
    [ qw(        V

    ) ],
    {
        'V' => \%V_of,
    },
    {
        'V' => 'MyTypes::AddressesSalutations',
    },
    {

        'V' => 'V',
    }
);

} # end BLOCK




package MyTypes::KVstringNiceListOfAddressesSalutations::_KVstringNiceListOfAddressesSalutations::XmlAttr;
use base qw(SOAP::WSDL::XSD::Typelib::AttributeSet);

{ # BLOCK to scope variables

my %K_of :ATTR(:get<K>);

__PACKAGE__->_factory(
    [ qw(
        K
    ) ],
    {

        K => \%K_of,
    },
    {
        K => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    }
);

} # end BLOCK



1;


=pod

=head1 NAME

MyTypes::KVstringNiceListOfAddressesSalutations

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
KVstringNiceListOfAddressesSalutations from the namespace http://tempuri2.org/.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * V




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::KVstringNiceListOfAddressesSalutations
   V =>  { # MyTypes::AddressesSalutations
     Recipients =>  { # MyTypes::Recipients
       To =>  $some_value, # string
       Cc =>  $some_value, # string
       Bcc =>  $some_value, # string
     },
     Salutation =>  $some_value, # string
   },
 },



=head2 attr

NOTE: Attribute documentation is experimental, and may be inaccurate.
See the correspondent WSDL/XML Schema if in question.

This class has additional attributes, accessibly via the C<attr()> method.

attr() returns an object of the class MyTypes::KVstringNiceListOfAddressesSalutations::_KVstringNiceListOfAddressesSalutations::XmlAttr.

The following attributes can be accessed on this object via the corresponding
get_/set_ methods:

=over

=item * K



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::string|SOAP::WSDL::XSD::Typelib::Builtin::string>.


=back




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

